select CF.CHAVE,CF.CTRC,CNH1.STATUS,CONCAT(CNH2.EMP_CODIGO,CNH2.SERIE,CNH2.CTRC) CTRC_NEW ,CNH2.STATUS STATUS_NEW
FROM CONFIRMAFACIL CF
JOIN CARGASSQL.dbo.NFR ON NFR.CHAVENFE = CF.CHAVE
JOIN CARGASSQL.dbo.CNH CNH1 ON CNH1.EMP_CODIGO=SUBSTRING(CF.CTRC,1,3) and CNH1.SERIE=SUBSTRING(CF.CTRC,4,1) and CNH1.CTRC =SUBSTRING(CF.CTRC,5,10)
JOIN CARGASSQL.dbo.CNH CNH2 ON CNH2.EMP_CODIGO=NFR.EMP_CODIGO and CNH2.SERIE=NFR.CNH_SERIE and CNH2.CTRC = NFR.CNH_CTRC
WHERE 
    CNH2.VALORNF>0
AND CNH2.TIPOCTRC IN (0,1)
AND CNH2.STATUS = 'I'
AND CNH1.STATUS <> 'I'



-- ALTER TABLE CONFIRMAFACIL ADD CTRC_OLD  VARCHAR(20) NULL;