-- 15/09/2021 14:07 - LISTA DE CODIGOS DEPARA ( SENIOR -> ORION )

USE [SIC]


CREATE TABLE ORION_DEPARA (
  ID                INT         NOT NULL IDENTITY PRIMARY KEY,
  CNPJ              VARCHAR(14) NOT NULL,
  OCORRENCIA_ID     INT         NOT NULL,
  CASUAL_ID         INT,
  TRANSPORTE_ID     INT,
  DT_ATUAL          DATETIME DEFAULT CURRENT_TIMESTAMP,
  OBSERVACAO        VARCHAR(250),
);

CREATE UNIQUE INDEX IDX_ORION_DEPARA_UK ON SIC.dbo.ORION_DEPARA(CNPJ,OCORRENCIA_ID);

INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',1,1,1,'ENTREGA REALIZADA NORMALMENTE')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',2,16,1,'ENTREGA FORA DA DATA PROGRAMAD')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',3,17,1,'RECUSA POR FALTA DE PEDIDO DE ')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',4,15,33,'RECUSA POR PEDIDO DE COMPRA CA')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',5,15,16,'FALTA DE ESPACO FISICO DEP. CL')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',6,15,19,'ENDEREÇO DO CLIENTE NÃO LOCALI')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',7,15,36,'DEVOLUCAO NAO AUTORIZADA PELO ')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',9,15,77,'MERCADORIA EM DESACORDO COM O ')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',10,15,37,'CLIENTE DESTINO SOMENTE RECEBE')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',11,10,1,'RECUSA POR DEFICIENCIA DA EMBA')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',12,15,38,'REDESPACHO NAO INDICADO')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',13,15,39,'TRANSP NAO ATENDE CIDADE DESTI')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',16,15,40,'PEDIDO DE COMPRAS EM DUPLICIDA')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',18,15,1,'MERCADORIA COM VOLUMES TROCADA')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',19,11,20,'REENTREGA SOLICITADA PELO CLIE')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',21,15,17,'ESTABELECIMENTO FECHADO')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',25,15,47,'MERCADORIA DEVOLVIDA')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',26,15,8,'NOTA FISCAL RETIDA PELA FISCAL')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',27,15,9,'MERCADORIA SINISTRADA NA COLET')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',28,15,3,'MERCADORIA RETIDA ATE SEGUNDA ')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',29,18,90,'CLIENTE RETIRA MERCADORIA NA T')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',30,15,78,'PROBLEMA COM A DOC. (NOTA FISC')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',33,1,1,'FALTA COM BUSCA/RECONFERENCIA')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',35,15,30,'QTD  PRODUTO EM DESACORDO C/ N')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',39,15,22,'CORTE DE CARGA NA PISTA')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',43,15,18,'FERIADO LOCAL/NACIONAL')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',44,15,15,'EXCESSO DE VEICULOS')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',46,15,26,'RESPONSAVEL DO RECEBIMENTO AUS')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',50,15,6,'GREVE NACIONAL (GREVE GERAL)')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',51,15,79,'MERCADORIA VENCIDA (DATA DE VA')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',58,15,4,'QUEBRA DO VEICULO DE ENTREGA')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',60,15,27,'ENDERECO DE ENTREGA ERRADO')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',77,15,35,'CLIENTE DESTINO MUDOU DE ENDER')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',78,9,12,'AVARIA TOTAL')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',79,3,11,'AVARIA PARCIAL')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',80,15,14,'EXTRAVIO TOTAL')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',81,8,13,'EXTRAVIO PARCIAL')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',84,15,91,'ENTREGA RETIDA PARA CONFERENCI')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',88,13,1,'RECUSADO, AGUARDANDO NEGOCIACA')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',92,15,1,'NOTA SERÁ ENVIADA A SEFAZ PARA')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',95,15,23,'AGUARDANDO VOO CONEXAO')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',98,15,88,'CHEGADA NA CIDADE OU FILIAL DE')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',203,15,89,'MERCADORIA LIBERADA PARA ENTREGA')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',302,15,89,'SAÍDA NO CENTRO DE DISTRIBUIÇÃO (CDOUT)')

--- 16/09/2021 09:42
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',100,15,89,'MERCADORIA LIBERADA PARA ENTREGA')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',101,15,89,'SAÍDA NO CENTRO DE DISTRIBUIÇÃO (CDOUT)')
INSERT INTO ORION_DEPARA ( CNPJ, OCORRENCIA_ID, CASUAL_ID, TRANSPORTE_ID, OBSERVACAO ) VALUES ('43854116',899,15,89,'PROCESSO DE TRANSPORTE INICIADO')
