-- 15/09/2021 16:45 -- RAIZ CNPJ - CLIENTES MONITORADOS - ORION

USE [SIC]

CREATE TABLE ORION_CLIENTES (
  CNPJ_RAIZ   VARCHAR(8) NOT NULL PRIMARY KEY,
  NOME        VARCHAR(60),
  DT_UPDATE   DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO ORION_CLIENTES (CNPJ_RAIZ,NOME) VALUES ('43854116','CEVA LOGISTICS LTDA')
