-- 15/09/2021 14:26 -- ORION OCORRENCIAS CASUAIS

USE [SIC]

CREATE TABLE ORION_CASUAL (
  ID                INT           NOT NULL    IDENTITY    PRIMARY KEY,
  CNPJ              VARCHAR(14)   NOT NULL,
  CASUAL_ID         INT           NOT NULL,
  DESCRICAO         VARCHAR(80)   NOT NULL,
  LIB_FATURAMENTO   VARCHAR(1)    NOT NULL,
  DT_ATUAL          DATETIME DEFAULT CURRENT_TIMESTAMP,
);

CREATE UNIQUE INDEX IDX_ORION_CASUAL_UK ON SIC.dbo.ORION_CASUAL(CNPJ,CASUAL_ID);

INSERT INTO ORION_CASUAL(CNPJ,CASUAL_ID,DESCRICAO,LIB_FATURAMENTO) VALUES ( '43854116',01,'ENTREGUE -  NORMAL','S');
INSERT INTO ORION_CASUAL(CNPJ,CASUAL_ID,DESCRICAO,LIB_FATURAMENTO) VALUES ( '43854116',02,'ENTREGUE - EXTRAVIO PARCIAL','S');
INSERT INTO ORION_CASUAL(CNPJ,CASUAL_ID,DESCRICAO,LIB_FATURAMENTO) VALUES ( '43854116',03,'ENTREGUE - MERCADORIA AVARIADA','S');
INSERT INTO ORION_CASUAL(CNPJ,CASUAL_ID,DESCRICAO,LIB_FATURAMENTO) VALUES ( '43854116',04,'ENTREGUE - EMBALAGEM AVARIADA','S');
INSERT INTO ORION_CASUAL(CNPJ,CASUAL_ID,DESCRICAO,LIB_FATURAMENTO) VALUES ( '43854116',05,'ENTREGUE - FALTA/DIVERG. DOC.','S');
INSERT INTO ORION_CASUAL(CNPJ,CASUAL_ID,DESCRICAO,LIB_FATURAMENTO) VALUES ( '43854116',06,'RECUSA - FALTA/DIVERG. DOC.','S');
INSERT INTO ORION_CASUAL(CNPJ,CASUAL_ID,DESCRICAO,LIB_FATURAMENTO) VALUES ( '43854116',07,'RECUSA - DIVERGENCIA NO PEDIDO','S');
INSERT INTO ORION_CASUAL(CNPJ,CASUAL_ID,DESCRICAO,LIB_FATURAMENTO) VALUES ( '43854116',08,'RECUSA - EXTRAVIO PARCIAL','S');
INSERT INTO ORION_CASUAL(CNPJ,CASUAL_ID,DESCRICAO,LIB_FATURAMENTO) VALUES ( '43854116',09,'RECUSA - MERCADORIA AVARIADA','N');
INSERT INTO ORION_CASUAL(CNPJ,CASUAL_ID,DESCRICAO,LIB_FATURAMENTO) VALUES ( '43854116',10,'RECUSA - EMBALAGEM AVARIADA','S');
INSERT INTO ORION_CASUAL(CNPJ,CASUAL_ID,DESCRICAO,LIB_FATURAMENTO) VALUES ( '43854116',11,'REENTREGA','S');
INSERT INTO ORION_CASUAL(CNPJ,CASUAL_ID,DESCRICAO,LIB_FATURAMENTO) VALUES ( '43854116',12,'NAO ENTREGUE','S');
INSERT INTO ORION_CASUAL(CNPJ,CASUAL_ID,DESCRICAO,LIB_FATURAMENTO) VALUES ( '43854116',13,'RECUSA - OUTROS','S');
INSERT INTO ORION_CASUAL(CNPJ,CASUAL_ID,DESCRICAO,LIB_FATURAMENTO) VALUES ( '43854116',14,'DEVOLUCAO','N');
INSERT INTO ORION_CASUAL(CNPJ,CASUAL_ID,DESCRICAO,LIB_FATURAMENTO) VALUES ( '43854116',15,'TRANSPORTE EM ANDAMENTO','N');
INSERT INTO ORION_CASUAL(CNPJ,CASUAL_ID,DESCRICAO,LIB_FATURAMENTO) VALUES ( '43854116',16,'ENTREGUE  - FORA DT PROGRAMADA','S');
INSERT INTO ORION_CASUAL(CNPJ,CASUAL_ID,DESCRICAO,LIB_FATURAMENTO) VALUES ( '43854116',17,'RECUSA - FALTA PEDIDO COMPRA','S');
INSERT INTO ORION_CASUAL(CNPJ,CASUAL_ID,DESCRICAO,LIB_FATURAMENTO) VALUES ( '43854116',18,'CLIENTE RETIRA','S');
INSERT INTO ORION_CASUAL(CNPJ,CASUAL_ID,DESCRICAO,LIB_FATURAMENTO) VALUES ( '43854116',19,'GESTAO NEGOCIOS SIT','N');
