-- 15/09/2021 14:26 -- OCORRÊNCIAS - ORION

USE [SIC]

CREATE TABLE ORION_OCORRENCIAS (
  ID                  INT           NOT NULL    IDENTITY    PRIMARY KEY,
  CNPJ                VARCHAR(14)   NOT NULL,
  DOCUMENTO           VARCHAR(20),
  CHAVE               VARCHAR(44),
  CHAVEORIGINAL       VARCHAR(44),
  DT_ATUAL            DATETIME DEFAULT CURRENT_TIMESTAMP,
  DT_OCORRENCIA       DATETIME,
  DT_SOLUCAO          DATETIME,
  DT_ENVIO            DATETIME,
  REPLICAR            VARCHAR(1)  DEFAULT 'S',
  LATITUDE            VARCHAR(20) DEFAULT '',
  LONGITUDE           VARCHAR(20) DEFAULT '',
  OBSERVACAO          VARCHAR(2000),
  OCORR301            INT,
  OCORR302            INT,
  OCORRCASUAL         INT,
  OCORRTRANSPORTE     INT,
  OCORRSIMPLIFICADA   INT,
  URL_ENDPOINT        VARCHAR(80),
  TIPOIMAGEM          VARCHAR(2)     DEFAULT '1',  
  RECEBEDOR_DOC       VARCHAR(40),
  RECEBEDOR_NOME      VARCHAR(60),
  DT_CREATE           DATETIME DEFAULT CURRENT_TIMESTAMP,
  DT_SEND             DATETIME,
  RESPOSTA_MSG        VARCHAR(2000),
  RESPOSTA_STATUS     INT,
  RESPOSTA_PROTOCOLO  VARCHAR(60),
  RESPOSTA_REENVIO    INT DEFAULT 0,
  CdEmpresa           INT,
  NrSeqControle       BIGINT,
  CdSequencia         INT,
  FLAG_SEND           INT NOT NULL DEFAULT 0
);

CREATE INDEX IDX_ORION_OCORRENCIAS_DOCUMENTO  ON ORION_OCORRENCIAS (DOCUMENTO);
CREATE INDEX IDX_ORION_OCORRENCIAS_SEND       ON ORION_OCORRENCIAS (FLAG_SEND,DT_CREATE);
CREATE INDEX IDX_ORION_OCORRENCIAS_SENIOR     ON ORION_OCORRENCIAS (CdEmpresa,NrSeqControle,CdSequencia);

ALTER TABLE ORION_OCORRENCIAS ADD CONSTRAINT FK_ORION_OCORRENCIAS_DOCUMENTO 
FOREIGN KEY (DOCUMENTO) REFERENCES ORION_CTE(DOCUMENTO);
