-- 15/09/2021 14:26 -- CTEs MONITORADOS - ORION

USE [SIC]

CREATE TABLE ORION_CTE (
  DOCUMENTO             VARCHAR(20) NOT NULL PRIMARY KEY,
  CHAVE                 VARCHAR(44),
  PROTOCOLO             VARCHAR(80),
  EMBARCADOR            VARCHAR(14) NOT NULL,
  DT_ATUAL              DATETIME DEFAULT CURRENT_TIMESTAMP,
  DT_EMISSAO            DATETIME NOT NULL,
  DT_EMBARQUE           DATETIME,
  DT_CHEGADA            DATETIME,
  DT_ENTREGA            DATETIME,
  DT_PREVISAO           DATETIME,
  DT_PREV_ORIGINAL      DATETIME,
  DT_AGENDAMENTO        DATETIME,
  VALOR                 NUMERIC,
  DESTINATARIO          VARCHAR(14) NOT NULL,
  TRANSPORTADOR         VARCHAR(14) NOT NULL,
  FLAG_COMPROVANTE      INT NOT NULL DEFAULT 0,
  JSON_COMPROVANTE      NVARCHAR(MAX),
  DT_ENVIO              DATETIME,      -- DATA DO ENVIO DO COMPROVANTE
  DT_VALIDACAO          DATETIME,      -- DATA DE VALIDAÇÃO DA CARGA / RECEBIMENTO DO IDPKCARGA
  DT_UPDATE             DATETIME DEFAULT CURRENT_TIMESTAMP,
  CdEmpresa             INT,
  NrSeqControle         BIGINT,
  NrDoctoFiscal         BIGINT,
  FASE_ID               INT NOT NULL DEFAULT 0
);

CREATE INDEX IDX_ORION_CTR_SENIOR  ON ORION_CTE (CdEmpresa,NrSeqControle);
CREATE INDEX IDX_ORION_FIS_SENIOR  ON ORION_CTE (CdEmpresa,NrDoctoFiscal);
